---
apiVersion: v1
kind: Service
metadata:
  name: zooc
  labels:
    app: zookeeper-client
    name: zookeeper-client
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper-3
  type: LoadBalancer